/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.veronatrento.areacerchio;

import java.awt.Color;

/**
 *
 * @author mirkou
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        calcolaBtn = new javax.swing.JButton();
        raggioValue = new javax.swing.JTextField();
        risultatoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calcolo Area Cerchio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Raggio:");

        calcolaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calcolaBtn.setForeground(new java.awt.Color(51, 204, 0));
        calcolaBtn.setText("Calcola");
        calcolaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcolaBtnActionPerformed(evt);
            }
        });

        raggioValue.setActionCommand("<Not Set>");
        raggioValue.setAlignmentX(0.0F);
        raggioValue.setAlignmentY(0.0F);
        raggioValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raggioValueActionPerformed(evt);
            }
        });

        risultatoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        risultatoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        risultatoLabel.setText("Loading");
        risultatoLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raggioValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(calcolaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addComponent(risultatoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(raggioValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(calcolaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(risultatoLabel)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raggioValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raggioValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raggioValueActionPerformed

    private void calcolaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcolaBtnActionPerformed
        // TODO add your handling code here:
        double raggio;
        double area;
        
        try{
            String sRaggio = raggioValue.getText();
            raggio = Double.parseDouble(sRaggio);
            
            if(raggio > 0 && raggio <= 100){
                Cerchio cerchio = new Cerchio(raggio);
                
                area = cerchio.getArea();
                risultatoLabel.setForeground(Color.black);
                risultatoLabel.setText(Double.toString(area));
                
            } else {
                throw new Exception("Il raggio deve essere compreso tra 1 e 100");
            }
                
        } catch (Exception x){
            risultatoLabel.setForeground(Color.red);
            risultatoLabel.setText(x.getMessage());
        }
        
        
        
        
              
    }//GEN-LAST:event_calcolaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcolaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField raggioValue;
    private javax.swing.JLabel risultatoLabel;
    // End of variables declaration//GEN-END:variables
}
